In [1]:
import torch

d:\PythonProject\pythonProject\python_learning\pytorch\.venv\Lib\site-packages\torch\_subclasses\functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [3]:
#1.张量的加法
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
c = a + b
print("Tensor addition:\n",c)

Tensor addition:
 tensor([[ 6,  8],
        [10, 12]])


In [5]:
#2.张量的乘法
d = a * b
print("Tensor multiplication:\n",d)

Tensor multiplication:
 tensor([[ 5, 12],
        [21, 32]])


In [7]:
#3.张量的减法
e = b - a
print("Tensor subtraction:\n",e)

Tensor subtraction:
 tensor([[4, 4],
        [4, 4]])


In [8]:
#4.张量矩阵乘法
f = torch.matmul(a,b)
print("Tensor matrix multiplication:\n",f)


Tensor matrix multiplication:
 tensor([[19, 22],
        [43, 50]])


In [10]:
#5.张量逐个元素乘法
g = a * b
print("Tensor element-wise multiplication:\n",g)

Tensor element-wise multiplication:
 tensor([[ 5, 12],
        [21, 32]])


In [12]:
#6.张量拼接cat(dim=0 按照第一个维度、行拼接; dim=1 按照第二个维度、列拼接)
h = torch.cat([a,b],dim=0)
print("Tensor concatenation along dim=0:\n",h)
i = torch.cat([a,b],dim=1)
print("Tensor concatenation along dim=1:\n",i)
j = torch.cat([a,b],dim=-1)#-1表示最后一个维度
print("Tensor concatenation along dim=-1:\n",j)

Tensor concatenation along dim=0:
 tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
Tensor concatenation along dim=1:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
Tensor concatenation along dim=-1:
 tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
