In [11]:
import torch

In [12]:
#1.创建一个未初始化的张量
x = torch.empty(5,3)
print("Empty Tensor:",x)

Empty Tensor: tensor([[5.6757e+14, 1.7320e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [13]:
"Empty Tensor:",x

('Empty Tensor:',
 tensor([[5.6757e+14, 1.7320e-42, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]))

In [14]:
#2.创建一个随机初始化的张量
x = torch.rand(5,3)
print("Random Tensor:\n",x)


Random Tensor:
 tensor([[0.6155, 0.9503, 0.9371],
        [0.7410, 0.4984, 0.7664],
        [0.3366, 0.5624, 0.9840],
        [0.5494, 0.2191, 0.7545],
        [0.1093, 0.3201, 0.7509]])


In [ ]:
x = torch.randn(5,3)#根据正态分布进行随机初始化
print("random tensor with normal distribution:\n",x)

random tensor with normal distribution:
 tensor([[-0.2455,  1.8391, -0.5365],
        [ 0.3687, -0.7820, -2.1180],
        [-2.2094, -2.5582, -0.6608],
        [ 0.1025,  0.2464,  0.8659],
        [-0.0459, -0.0698,  1.1675]])


In [ ]:
#3. 创建一个全零张量，并指定数据类型为long
x = torch.zeros(5,3,dtype=torch.long)
print("Zero Tensor:\n",x)

Zero Tensor:
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
#4.直接从数据创建张量
x = torch.tensor([5.5,3])
print("Directly create tensor from data:\n",x)

Directly create tensor from data:
 tensor([5.5000, 3.0000])


In [21]:
x = torch.ones(3,4)
y = torch.ones_like(x)#根据x的形状创建一个全1张量
print("Ones like x:\n",y)

Ones like x:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [22]:
x = torch.tensor([[1,2],[3,4]])
print("Shape of x:",x.shape)
print("Datatype of x:",x.dtype)
print(x.type)

Shape of x: torch.Size([2, 2])
Datatype of x: torch.int64
<built-in method type of Tensor object at 0x00000278AC2D7890>
