In [1]:

import torch

d:\PythonProject\pythonProject\python_learning\pytorch\.venv\Lib\site-packages\torch\_subclasses\functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
#1.reshape:改变张量形状
x = torch.arange(1,13)
print("Original tensor:\n",x)
y = x.reshape(3,4)
print("Reshaped tensor (3x4):\n",y)

Original tensor:
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
Reshaped tensor (3x4):
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [4]:
#2.view：与reshape类似，但是要求张量是连续的
print("View to 4x3 tensor:\n",y.view(4,3))

View to 4x3 tensor:
 tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [12]:
#3.transpose:转置张量
x = torch.randn(2,3,4)#创建2个3行4列的随机张量
print("Original tensor:\n",x)
y = x.transpose(0,2).shape#交换第0维和第2维，即将2个3行4列的张量变为4个3行2列的张量
print("Transposed tensor (dim1<->dim2):\n",y)

Original tensor:
 tensor([[[-1.3331, -0.1631,  0.1353,  1.3292],
         [ 1.1319,  0.7104,  1.3014, -1.2171],
         [-1.3873,  1.7657,  0.0050, -1.6119]],

        [[-1.1619, -1.1180, -1.0311,  0.9784],
         [ 0.7051, -1.4028,  1.0039, -1.2715],
         [-0.1073, -0.1494, -1.3585, -0.6084]]])
Transposed tensor (dim1<->dim2):
 torch.Size([4, 3, 2])


In [16]:
#4.squeeze / unsqueeze:删除/增加维度
x = torch.randn(1,3,1,4)
y = x.squeeze()#删除所有维度为1的维度
print("Squeezed tensor shape:\n",y.shape)
z = y.unsqueeze(0)#在第0维增加一个维度
print("Unsqueezed tensor shape:\n",z.shape)


Squeezed tensor shape:
 torch.Size([3, 4])
Unsqueezed tensor shape:
 torch.Size([1, 3, 4])


In [17]:
#什么是连续张量？
#连续张量：张量的元素在内存中按照其索引顺序连续存储。
#非连续张量：张量的元素在内存中不是按照其索引顺序



In [20]:
#连续张量的例子
#创建一个连续张量
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Is 'a' contiguous?:", a.is_contiguous())
#可以直接使用view方法改变形状
b = a.view(3, 2)
print("Reshaped tensor 'b' using view:\n", b)

Is 'a' contiguous?: True
Reshaped tensor 'b' using view:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [22]:
#非连续张量的例子
#通过转置创建一个非连续张量
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = a.transpose(0, 1)
print("Is 'b' contiguous?:", b.is_contiguous())
#尝试使用view方法会报错


Is 'b' contiguous?: False


In [23]:
#如果需要对非连续张量使用view方法，可以先调用.contiguous()方法将其转换为连续张量，然后再使用view方法。
c = b.contiguous().view(3, 2)
print("Reshaped tensor 'c' after making contiguous:\n", c)


Reshaped tensor 'c' after making contiguous:
 tensor([[1, 4],
        [2, 5],
        [3, 6]])
